source 'https://github.com/CocoaPods/Specs.git'

workspace 'Anypic'

use_frameworks!

pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'FormatterKit'
pod 'UIImageEffects'
